// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/abonnement/concierge-pro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/abonnement/concierge-pro">> = Specific
  const handler = {} as typeof import("../../src/app/abonnement/concierge-pro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/cadences/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cadences">> = Specific
  const handler = {} as typeof import("../../src/app/cadences/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/complete-registration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/complete-registration">> = Specific
  const handler = {} as typeof import("../../src/app/complete-registration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/concierge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/concierge">> = Specific
  const handler = {} as typeof import("../../src/app/concierge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/concierges/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/concierges/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/concierges/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/artisans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/artisans">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/artisans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/conciergeries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/conciergeries">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/conciergeries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/controle/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/controle">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/controle/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/decisions-architecture/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/decisions-architecture">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/decisions-architecture/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/demandes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/demandes">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/demandes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/developpement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/developpement">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/developpement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/developpement/personas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/developpement/personas">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/developpement/personas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/missions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/missions">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/missions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/pilotage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/pilotage">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/pilotage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/proprietaires/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/proprietaires">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/proprietaires/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/admin/utilisateurs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admin/utilisateurs">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/admin/utilisateurs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/cadences/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/cadences">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/cadences/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/alertes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/alertes">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/alertes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/billing">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/contacts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/contacts">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/contacts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/contract-templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/contract-templates">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/contract-templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/decoration-ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/decoration-ai">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/decoration-ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/demandes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/demandes">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/demandes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/equipe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/equipe">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/equipe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/fiche/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/fiche">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/fiche/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/finances/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/finances/overview">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/finances/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/finances/simulation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/finances/simulation">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/finances/simulation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/logements/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/logements/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/logements/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/logements/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/logements/create">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/logements/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/logements/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/logements/overview">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/logements/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/logements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/logements">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/logements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/maintenance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/maintenance">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/maintenance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/messages">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/missions/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/missions/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/missions/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/missions/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/missions/overview">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/missions/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/missions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/missions">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/missions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/objectifs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/objectifs">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/objectifs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/planning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/planning">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/planning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/pricing">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/profile">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/proprietaires/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/proprietaires/overview">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/proprietaires/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/recherche/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/recherche">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/recherche/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/sejours/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/sejours">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/sejours/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/services-packages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/services-packages">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/services-packages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/settings">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/stocks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/stocks">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/stocks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/concierge/urgences/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/concierge/urgences">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/concierge/urgences/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/alertes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/alertes">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/alertes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/conciergerie/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/conciergerie/overview">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/conciergerie/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/conciergerie/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/conciergerie">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/conciergerie/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/conciergerie/partenaires/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/conciergerie/partenaires">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/conciergerie/partenaires/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/concierges/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/concierges">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/concierges/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/contacts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/contacts">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/contacts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/demandes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/demandes">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/demandes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/devis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/devis">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/devis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/documents">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/factures/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/factures">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/factures/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/finances/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/finances/overview">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/finances/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/litiges/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/litiges">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/litiges/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/logements/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/logements/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/logements/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/logements/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/logements/create">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/logements/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/logements/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/logements/overview">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/logements/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/logements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/logements">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/logements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/messages">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/mission-urgente/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/mission-urgente">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/mission-urgente/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/missions/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/missions/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/missions/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/missions/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/missions/new">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/missions/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/missions/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/missions/overview">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/missions/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/missions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/missions">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/missions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/missions/voyageurs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/missions/voyageurs">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/missions/voyageurs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/objectifs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/objectifs">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/objectifs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/planning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/planning">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/planning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/reglement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/reglement">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/reglement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/settings">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/owner/stocks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/owner/stocks">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/owner/stocks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/provider/alertes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/provider/alertes">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/provider/alertes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/provider/clients/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/provider/clients/overview">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/provider/clients/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/provider/clients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/provider/clients">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/provider/clients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/provider/devis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/provider/devis">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/provider/devis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/provider/finances/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/provider/finances/overview">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/provider/finances/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/provider/interventions/overview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/provider/interventions/overview">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/provider/interventions/overview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/provider/interventions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/provider/interventions">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/provider/interventions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/provider/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/provider/messages">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/provider/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/provider/objectifs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/provider/objectifs">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/provider/objectifs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/provider/outils/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/provider/outils">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/provider/outils/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/provider/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/provider">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/provider/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/provider/planning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/provider/planning">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/provider/planning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/provider/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/provider/settings">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/provider/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/design-system/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design-system">> = Specific
  const handler = {} as typeof import("../../src/app/design-system/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/design-system/visuels/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design-system/visuels">> = Specific
  const handler = {} as typeof import("../../src/app/design-system/visuels/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/home">> = Specific
  const handler = {} as typeof import("../../src/app/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/mission-urgente/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mission-urgente">> = Specific
  const handler = {} as typeof import("../../src/app/mission-urgente/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/owner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/owner">> = Specific
  const handler = {} as typeof import("../../src/app/owner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/parcours/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/parcours">> = Specific
  const handler = {} as typeof import("../../src/app/parcours/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/planning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planning">> = Specific
  const handler = {} as typeof import("../../src/app/planning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/premium-owner-dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/premium-owner-dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/premium-owner-dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/provider/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/provider">> = Specific
  const handler = {} as typeof import("../../src/app/provider/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/control-tower/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/control-tower">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/control-tower/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/operations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/operations">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/operations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/overview">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/project-advisor/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/project-advisor">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/project-advisor/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/prompt-library/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/prompt-library">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/prompt-library/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/[[...nextauth]]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[[...nextauth]]">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/[[...nextauth]]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/dev-workspace-login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/dev-workspace-login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/dev-workspace-login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/history">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/invoices/[id]/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/invoices/[id]/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/invoices/[id]/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/invoices/[id]/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/invoices/[id]/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/invoices/[id]/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/sync/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/sync">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/sync/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/billing/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/billing/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/concierge/daily-checklist/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/concierge/daily-checklist">> = Specific
  const handler = {} as typeof import("../../src/app/api/concierge/daily-checklist/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/concierge/decoration-assistant/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/concierge/decoration-assistant">> = Specific
  const handler = {} as typeof import("../../src/app/api/concierge/decoration-assistant/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/concierge/intervention-zone/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/concierge/intervention-zone">> = Specific
  const handler = {} as typeof import("../../src/app/api/concierge/intervention-zone/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/concierge/maintenance/[id]/media/[mediaId]/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/concierge/maintenance/[id]/media/[mediaId]/download">> = Specific
  const handler = {} as typeof import("../../src/app/api/concierge/maintenance/[id]/media/[mediaId]/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/concierge/maintenance/[id]/media/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/concierge/maintenance/[id]/media">> = Specific
  const handler = {} as typeof import("../../src/app/api/concierge/maintenance/[id]/media/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/concierge/maintenance/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/concierge/maintenance/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/concierge/maintenance/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/concierge/maintenance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/concierge/maintenance">> = Specific
  const handler = {} as typeof import("../../src/app/api/concierge/maintenance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/concierge/match-owner-requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/concierge/match-owner-requests">> = Specific
  const handler = {} as typeof import("../../src/app/api/concierge/match-owner-requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/concierge/optimized-routes/optimize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/concierge/optimized-routes/optimize">> = Specific
  const handler = {} as typeof import("../../src/app/api/concierge/optimized-routes/optimize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/concierge/optimized-routes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/concierge/optimized-routes">> = Specific
  const handler = {} as typeof import("../../src/app/api/concierge/optimized-routes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/concierge/reservations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/concierge/reservations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/concierge/reservations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/concierge/reservations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/concierge/reservations">> = Specific
  const handler = {} as typeof import("../../src/app/api/concierge/reservations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/concierge/stays/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/concierge/stays">> = Specific
  const handler = {} as typeof import("../../src/app/api/concierge/stays/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/concierge/team/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/concierge/team/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/concierge/team/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/concierge/team/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/concierge/team">> = Specific
  const handler = {} as typeof import("../../src/app/api/concierge/team/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/disputes/[id]/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/disputes/[id]/export">> = Specific
  const handler = {} as typeof import("../../src/app/api/disputes/[id]/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/disputes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/disputes">> = Specific
  const handler = {} as typeof import("../../src/app/api/disputes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/geocode/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/geocode">> = Specific
  const handler = {} as typeof import("../../src/app/api/geocode/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/housing/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/housing/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/housing/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/housing/photos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/housing/photos">> = Specific
  const handler = {} as typeof import("../../src/app/api/housing/photos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/housing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/housing">> = Specific
  const handler = {} as typeof import("../../src/app/api/housing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inspections/[id]/checklist/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inspections/[id]/checklist">> = Specific
  const handler = {} as typeof import("../../src/app/api/inspections/[id]/checklist/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inspections/[id]/media/[mediaId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inspections/[id]/media/[mediaId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/inspections/[id]/media/[mediaId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inspections/[id]/media/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inspections/[id]/media">> = Specific
  const handler = {} as typeof import("../../src/app/api/inspections/[id]/media/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inspections/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inspections/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/inspections/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inspections/[id]/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inspections/[id]/submit">> = Specific
  const handler = {} as typeof import("../../src/app/api/inspections/[id]/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/inspections/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/inspections">> = Specific
  const handler = {} as typeof import("../../src/app/api/inspections/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/invoices/[id]/document/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invoices/[id]/document">> = Specific
  const handler = {} as typeof import("../../src/app/api/invoices/[id]/document/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/invoices/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invoices/[id]/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/invoices/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/invoices/from-quote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invoices/from-quote">> = Specific
  const handler = {} as typeof import("../../src/app/api/invoices/from-quote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/invoices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/invoices">> = Specific
  const handler = {} as typeof import("../../src/app/api/invoices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/kpis/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/kpis/overview">> = Specific
  const handler = {} as typeof import("../../src/app/api/kpis/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/messages/conversations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/conversations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/messages/conversations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/messages/conversations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/messages/conversations">> = Specific
  const handler = {} as typeof import("../../src/app/api/messages/conversations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/missions/[id]/files/[proofId]/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/missions/[id]/files/[proofId]/download">> = Specific
  const handler = {} as typeof import("../../src/app/api/missions/[id]/files/[proofId]/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/missions/[id]/files/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/missions/[id]/files">> = Specific
  const handler = {} as typeof import("../../src/app/api/missions/[id]/files/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/missions/[id]/provider-interventions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/missions/[id]/provider-interventions">> = Specific
  const handler = {} as typeof import("../../src/app/api/missions/[id]/provider-interventions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/missions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/missions/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/missions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/missions/kpis/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/missions/kpis">> = Specific
  const handler = {} as typeof import("../../src/app/api/missions/kpis/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/missions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/missions">> = Specific
  const handler = {} as typeof import("../../src/app/api/missions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/onboarding-events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/onboarding-events">> = Specific
  const handler = {} as typeof import("../../src/app/api/onboarding-events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/owner-invitations/[id]/resend/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/owner-invitations/[id]/resend">> = Specific
  const handler = {} as typeof import("../../src/app/api/owner-invitations/[id]/resend/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/owner-invitations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/owner-invitations">> = Specific
  const handler = {} as typeof import("../../src/app/api/owner-invitations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/owner/reservations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/owner/reservations">> = Specific
  const handler = {} as typeof import("../../src/app/api/owner/reservations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pricing/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/pricing/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pricing/property-rules/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing/property-rules/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/pricing/property-rules/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pricing/property-rules/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing/property-rules">> = Specific
  const handler = {} as typeof import("../../src/app/api/pricing/property-rules/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pricing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing">> = Specific
  const handler = {} as typeof import("../../src/app/api/pricing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pricing/segments/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing/segments/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/pricing/segments/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pricing/segments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing/segments">> = Specific
  const handler = {} as typeof import("../../src/app/api/pricing/segments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pricing/strategy-scenarios/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing/strategy-scenarios/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/pricing/strategy-scenarios/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/pricing/strategy-scenarios/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pricing/strategy-scenarios">> = Specific
  const handler = {} as typeof import("../../src/app/api/pricing/strategy-scenarios/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profiles/avatar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles/avatar">> = Specific
  const handler = {} as typeof import("../../src/app/api/profiles/avatar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profiles/concierges/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles/concierges">> = Specific
  const handler = {} as typeof import("../../src/app/api/profiles/concierges/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profiles/current/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles/current">> = Specific
  const handler = {} as typeof import("../../src/app/api/profiles/current/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profiles/housing/from-quote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles/housing/from-quote">> = Specific
  const handler = {} as typeof import("../../src/app/api/profiles/housing/from-quote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profiles/housing/owners/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles/housing/owners">> = Specific
  const handler = {} as typeof import("../../src/app/api/profiles/housing/owners/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profiles/owners/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles/owners">> = Specific
  const handler = {} as typeof import("../../src/app/api/profiles/owners/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profiles/providers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles/providers">> = Specific
  const handler = {} as typeof import("../../src/app/api/profiles/providers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profiles/public-concierges/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles/public-concierges">> = Specific
  const handler = {} as typeof import("../../src/app/api/profiles/public-concierges/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profiles/public/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles/public/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/profiles/public/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profiles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles">> = Specific
  const handler = {} as typeof import("../../src/app/api/profiles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/profiles/workspaces/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profiles/workspaces">> = Specific
  const handler = {} as typeof import("../../src/app/api/profiles/workspaces/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/provider/alerts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/provider/alerts/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/provider/alerts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/provider/alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/provider/alerts">> = Specific
  const handler = {} as typeof import("../../src/app/api/provider/alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/provider/clients/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/provider/clients/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/provider/clients/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/provider/clients/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/provider/clients">> = Specific
  const handler = {} as typeof import("../../src/app/api/provider/clients/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/provider/interventions/[id]/invoice/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/provider/interventions/[id]/invoice">> = Specific
  const handler = {} as typeof import("../../src/app/api/provider/interventions/[id]/invoice/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/provider/interventions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/provider/interventions/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/provider/interventions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/provider/interventions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/provider/interventions">> = Specific
  const handler = {} as typeof import("../../src/app/api/provider/interventions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/provider/messages/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/provider/messages/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/provider/messages/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/provider/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/provider/messages">> = Specific
  const handler = {} as typeof import("../../src/app/api/provider/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/provider/profile-documents/[id]/download/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/provider/profile-documents/[id]/download">> = Specific
  const handler = {} as typeof import("../../src/app/api/provider/profile-documents/[id]/download/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/provider/profile-documents/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/provider/profile-documents/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/provider/profile-documents/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/provider/profile-documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/provider/profile-documents">> = Specific
  const handler = {} as typeof import("../../src/app/api/provider/profile-documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/provider/workspace/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/provider/workspace">> = Specific
  const handler = {} as typeof import("../../src/app/api/provider/workspace/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quotes/[id]/document/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quotes/[id]/document">> = Specific
  const handler = {} as typeof import("../../src/app/api/quotes/[id]/document/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quotes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quotes/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/quotes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quotes/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quotes/[id]/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/quotes/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quotes/[id]/view/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quotes/[id]/view">> = Specific
  const handler = {} as typeof import("../../src/app/api/quotes/[id]/view/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quotes/from-mission/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quotes/from-mission">> = Specific
  const handler = {} as typeof import("../../src/app/api/quotes/from-mission/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/quotes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quotes">> = Specific
  const handler = {} as typeof import("../../src/app/api/quotes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reservations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reservations/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/reservations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reviews">> = Specific
  const handler = {} as typeof import("../../src/app/api/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/search/owner-listings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/search/owner-listings">> = Specific
  const handler = {} as typeof import("../../src/app/api/search/owner-listings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/service-request-recipients/[id]/prepare-quote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/service-request-recipients/[id]/prepare-quote">> = Specific
  const handler = {} as typeof import("../../src/app/api/service-request-recipients/[id]/prepare-quote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/service-request-recipients/[id]/respond/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/service-request-recipients/[id]/respond">> = Specific
  const handler = {} as typeof import("../../src/app/api/service-request-recipients/[id]/respond/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/service-requests/[id]/select/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/service-requests/[id]/select">> = Specific
  const handler = {} as typeof import("../../src/app/api/service-requests/[id]/select/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/service-requests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/service-requests">> = Specific
  const handler = {} as typeof import("../../src/app/api/service-requests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/services/contract-templates/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/services/contract-templates">> = Specific
  const handler = {} as typeof import("../../src/app/api/services/contract-templates/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/services/contracts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/services/contracts/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/services/contracts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/services/contracts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/services/contracts">> = Specific
  const handler = {} as typeof import("../../src/app/api/services/contracts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/services/packages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/services/packages">> = Specific
  const handler = {} as typeof import("../../src/app/api/services/packages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/services/pricing-packages/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/services/pricing-packages/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/services/pricing-packages/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/services/pricing-packages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/services/pricing-packages">> = Specific
  const handler = {} as typeof import("../../src/app/api/services/pricing-packages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/services/service_pricing/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/services/service_pricing/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/services/service_pricing/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/services/service_pricing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/services/service_pricing">> = Specific
  const handler = {} as typeof import("../../src/app/api/services/service_pricing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/services/services-catalog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/services/services-catalog">> = Specific
  const handler = {} as typeof import("../../src/app/api/services/services-catalog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/urgent-missions/[id]/accept/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/urgent-missions/[id]/accept">> = Specific
  const handler = {} as typeof import("../../src/app/api/urgent-missions/[id]/accept/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/urgent-missions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/urgent-missions">> = Specific
  const handler = {} as typeof import("../../src/app/api/urgent-missions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workflow-events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workflow-events">> = Specific
  const handler = {} as typeof import("../../src/app/api/workflow-events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
