var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/pricing/route.js")
R.c("server/chunks/[root-of-the-server]__84ecb7a8._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_b7faa18d._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_da86c597._.js")
R.c("server/chunks/node_modules_42103433._.js")
R.c("server/chunks/_next-internal_server_app_api_pricing_route_actions_15721054.js")
R.m(259906)
module.exports=R.m(259906).exports
