var R=require("../../../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/concierge/maintenance/[id]/media/[mediaId]/download/route.js")
R.c("server/chunks/[root-of-the-server]__0c040345._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_b7faa18d._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_da86c597._.js")
R.c("server/chunks/node_modules_42103433._.js")
R.c("server/chunks/3e585_api_concierge_maintenance_[id]_media_[mediaId]_download_route_actions_bb9f79f4.js")
R.m(138144)
module.exports=R.m(138144).exports
