var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/invoices/[id]/status/route.js")
R.c("server/chunks/[root-of-the-server]__1411c9f8._.js")
R.c("server/chunks/node_modules_b7faa18d._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_1e389dac.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_42103433._.js")
R.c("server/chunks/_da86c597._.js")
R.c("server/chunks/_next-internal_server_app_api_invoices_[id]_status_route_actions_eb5b2863.js")
R.m(646726)
module.exports=R.m(646726).exports
