var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/kpis/overview/route.js")
R.c("server/chunks/[root-of-the-server]__093dc86b._.js")
R.c("server/chunks/node_modules_b7faa18d._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_7292c9c2.js")
R.c("server/chunks/_da86c597._.js")
R.c("server/chunks/node_modules_42103433._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/_next-internal_server_app_api_kpis_overview_route_actions_75916d9c.js")
R.m(799198)
module.exports=R.m(799198).exports
