var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/inspections/[id]/media/[mediaId]/route.js")
R.c("server/chunks/[root-of-the-server]__1be751ab._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_b7faa18d._.js")
R.c("server/chunks/_da86c597._.js")
R.c("server/chunks/node_modules_42103433._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/ce889_server_app_api_inspections_[id]_media_[mediaId]_route_actions_5f3c2a32.js")
R.m(46334)
module.exports=R.m(46334).exports
