var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/provider/profile-documents/[id]/download/route.js")
R.c("server/chunks/[root-of-the-server]__c01bc128._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_b7faa18d._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_da86c597._.js")
R.c("server/chunks/node_modules_42103433._.js")
R.c("server/chunks/ce889_server_app_api_provider_profile-documents_[id]_download_route_actions_93a83ad3.js")
R.m(31533)
module.exports=R.m(31533).exports
