var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/owner/factures/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__f486f1e2._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b63a0e1._.js")
R.c("server/chunks/ssr/_76da4dde._.js")
R.c("server/chunks/ssr/[root-of-the-server]__3224e5a4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1690ee0d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_2df23979._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/src_app_e491dc8a._.js")
R.c("server/chunks/ssr/src_app_error_tsx_ef715cc8._.js")
R.c("server/chunks/ssr/_61b58078._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_dashboard_layout_tsx_ebf7678c._.js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_owner_factures_page_actions_7cd729a6.js")
R.m(925703)
module.exports=R.m(925703).exports
