import type {
  GoNoGoRule,
  ImmediateActionGroup,
  InitialDiagnosticItem,
  IntegrationRecommendation,
  InterviewScript,
  LandingVariant,
  PrioritizedHypothesis,
  SurveyQuestion,
  ValidationKpi,
  ValidationScheduleEntry,
  ValidationTest,
} from "./types";

export const analyzedFiles = [
  "docs/master-plan-planetls.md",
  "src/app/dashboard/admin/(business)/pilotage/page.tsx",
  "src/app/dashboard/admin/(business)/pilotage/risk-register/riskData.ts",
  "src/app/abonnement/concierge-pro/ConciergeProSubscriptionPageClient.tsx",
];

export const exploitableJourneys = [
  "Propriétaire -> demande -> devis -> mission -> facture payée",
  "Conciergerie -> séjours -> planning -> coordination opérationnelle",
  "Mission -> intervention artisan -> preuve -> facture provider",
  "Abonnement Concierge PRO déjà relié à Stripe, mais non validé commercialement",
];

export const unnecessaryFeaturesForValidation = [
  "Marketplace nationale complète",
  "IA premium supplémentaire",
  "Nouveau dashboard complexe par profil",
  "Automatisation avancée de back-office",
  "Offres Enterprise ou multi-pays",
];

export const reusableComponents = [
  "DashboardLayout",
  "DashboardPanel",
  "RiskRegister",
  "StrategicDecisionAssistant",
  "Composants business-strategy réutilisables en lecture si besoin ultérieur",
];

export const unverifiableHypotheses = [
  "Densité marketplace réellement suffisante hors zone pilote",
  "Acceptation d'une commission au niveau national",
  "Valeur d'une offre multi-profils servie simultanément",
];

export const planLimits = [
  "Le plan repose d'abord sur des preuves terrain manuelles, pas sur un trafic massif.",
  "Les premiers résultats seront utiles mais encore fragiles statistiquement.",
  "Une fondatrice seule doit limiter le nombre de tests actifs en parallèle.",
];

export const initialDiagnostic: InitialDiagnosticItem[] = [
  {
    id: "diag-1",
    title: "État d'avancement observé",
    summary:
      "PlanetLS est déjà large fonctionnellement, avec des parcours métier crédibles, mais le modèle économique et le segment payeur restent non validés.",
  },
  {
    id: "diag-2",
    title: "Profils principaux",
    summary:
      "Les propriétaires, concierges indépendants, petites conciergeries et prestataires existent dans le produit, mais il serait risqué de tous tester avec la même promesse.",
  },
  {
    id: "diag-3",
    title: "Problèmes supposés",
    summary:
      "Les frictions les plus crédibles portent sur la dispersion des informations de séjour, la coordination des missions, le suivi des changements et la traçabilité entre propriétaire et conciergerie.",
  },
  {
    id: "diag-4",
    title: "Hypothèses les plus risquées",
    summary:
      "Les points les plus incertains sont la priorité réelle du problème, le meilleur premier segment payeur, la simplicité attendue du produit et le prix acceptable.",
  },
  {
    id: "diag-5",
    title: "Données manquantes",
    summary:
      "Il manque surtout des entretiens récents, des observations terrain, des essais d'offre pilote et des engagements concrets plus forts qu'une simple curiosité.",
  },
  {
    id: "diag-6",
    title: "Partie la plus testable rapidement",
    summary:
      "Le meilleur MVP proche du réel est le parcours conciergerie centré sur séjour -> informations voyageurs -> mission -> planning -> preuve, appuyé par l'offre Concierge PRO existante mais repositionnée comme pilote.",
  },
];

export const prioritizedHypotheses: PrioritizedHypothesis[] = [
  {
    id: "hyp-1",
    code: "H4",
    title: "Les concierges indépendants ou petites conciergeries sont le meilleur premier segment payeur.",
    importance: "Très élevée",
    uncertainty: "Très élevée",
    urgency: "Immédiate",
    wrongDecisionCost: "Élevé",
    priority: "critique",
  },
  {
    id: "hyp-2",
    code: "H2",
    title: "Les erreurs et oublis autour des séjours et missions sont assez douloureux pour déclencher une adoption.",
    importance: "Très élevée",
    uncertainty: "Élevée",
    urgency: "Immédiate",
    wrongDecisionCost: "Élevé",
    priority: "critique",
  },
  {
    id: "hyp-3",
    code: "H6",
    title: "Les conciergeries paieront un abonnement si PlanetLS simplifie réellement l'exploitation quotidienne.",
    importance: "Très élevée",
    uncertainty: "Très élevée",
    urgency: "Immédiate",
    wrongDecisionCost: "Très élevé",
    priority: "critique",
  },
  {
    id: "hyp-4",
    code: "H5",
    title: "Un parcours simple centré sur un usage essentiel vaut plus qu'une plateforme très large au démarrage.",
    importance: "Élevée",
    uncertainty: "Élevée",
    urgency: "Forte",
    wrongDecisionCost: "Élevé",
    priority: "prioritaire",
  },
  {
    id: "hyp-5",
    code: "H3",
    title: "La promesse de centralisation entre propriétaires, concierges et prestataires suscite un intérêt mesurable.",
    importance: "Élevée",
    uncertainty: "Élevée",
    urgency: "Forte",
    wrongDecisionCost: "Moyen à élevé",
    priority: "prioritaire",
  },
  {
    id: "hyp-6",
    code: "H7",
    title: "Un abonnement SaaS est plus simple à lancer qu'une logique de commission comme moteur principal.",
    importance: "Élevée",
    uncertainty: "Moyenne",
    urgency: "Forte",
    wrongDecisionCost: "Élevé",
    priority: "prioritaire",
  },
  {
    id: "hyp-7",
    code: "H10",
    title: "Une approche locale est plus réaliste qu'un lancement marketplace national immédiat.",
    importance: "Moyenne à élevée",
    uncertainty: "Élevée",
    urgency: "Forte",
    wrongDecisionCost: "Élevé",
    priority: "importante",
  },
];

export const validationSchedule: ValidationScheduleEntry[] = [
  {
    id: "schedule-1",
    window: "Jours 1 à 3",
    phase: "problem",
    focus: "Préparation, recrutement, cadrage des hypothèses critiques",
    actions: [
      "Finaliser scripts d'entretien et sondage.",
      "Préparer liste de 20 à 30 contacts répartis par segment.",
      "Choisir une zone pilote locale à privilégier.",
    ],
  },
  {
    id: "schedule-2",
    window: "Jours 4 à 10",
    phase: "problem",
    focus: "Validation du problème par entretiens, observation et sondage",
    actions: [
      "Conduire au moins 12 à 15 entretiens.",
      "Observer un parcours réel de réservation à mission.",
      "Lancer un sondage court et synthétiser les signaux communs.",
    ],
  },
  {
    id: "schedule-3",
    window: "Jours 11 à 14",
    phase: "interest",
    focus: "Tester les promesses et la compréhension de l'offre",
    actions: [
      "Créer deux landing pages de validation.",
      "Comparer les accroches et les demandes de démo.",
      "Préparer une démonstration guidée du parcours principal.",
    ],
  },
  {
    id: "schedule-4",
    window: "Jours 15 à 20",
    phase: "interest",
    focus: "Pilote manuel et usages réels",
    actions: [
      "Faire tourner 1 à 3 pilotes manuels.",
      "Suivre les frictions réelles et le niveau d'activation.",
      "Isoler le vrai MVP utile du reste du produit.",
    ],
  },
  {
    id: "schedule-5",
    window: "Jours 21 à 25",
    phase: "willingness_to_pay",
    focus: "Tester le prix et les formats d'offre",
    actions: [
      "Mener les entretiens de pricing.",
      "Comparer plusieurs formats de pilote.",
      "Préparer une proposition d'engagement plus forte qu'une liste d'attente.",
    ],
  },
  {
    id: "schedule-6",
    window: "Jours 26 à 30",
    phase: "willingness_to_pay",
    focus: "Clôture, décisions et go/no-go",
    actions: [
      "Obtenir des accords, acomptes ou refus motivés.",
      "Appliquer la grille GO / TEST MORE / PIVOT.",
      "Décider du segment prioritaire et de l'offre pilote suivante.",
    ],
  },
];

export const validationTests: ValidationTest[] = [
  {
    id: "test-1",
    number: 1,
    phase: "problem",
    title: "Entretiens propriétaires",
    objective: "Mesurer la réalité, la fréquence et le coût des problèmes de coordination côté propriétaire.",
    targetSegment: "Segment A - Propriétaires autonomes",
    testedHypothesis: "H1 / H2",
    riskAssessed: "Le problème pourrait être occasionnel ou jugé secondaire.",
    protocol: [
      "Contacter 6 à 8 propriétaires hors cercle intime.",
      "Conduire un entretien de 30 minutes centré sur la dernière situation réelle.",
      "Coder les réponses dans un tableau commun.",
    ],
    minimumParticipants: 6,
    recruitmentMode: "Réseau personnel élargi, groupes locaux, contacts d'hébergement",
    tools: ["Google Meet", "Notion ou Google Sheets", "Calendly gratuit"],
    prepTime: "2 h",
    executionTime: "5 h",
    estimatedCost: "0 à 20 EUR",
    collectedData: ["Outils utilisés", "Temps perdu", "Fréquence des erreurs", "Niveau de douleur"],
    primaryMetrics: ["% rencontrant le problème chaque semaine", "% classant le sujet dans le top 3 des difficultés"],
    secondaryMetrics: ["Temps hebdomadaire perdu", "Satisfaction de la solution actuelle"],
    validationThreshold: ">= 60 % rencontrent le problème régulièrement",
    uncertaintyThreshold: "35 % à 59 %",
    failureThreshold: "< 35 %",
    biases: ["Biais de récit a posteriori", "Participants trop proches"],
    followUpAction: "Si faible douleur, réduire l'angle propriétaire comme cible primaire.",
    deliverable: "Synthèse propriétaire + verbatims structurés",
  },
  {
    id: "test-2",
    number: 2,
    phase: "problem",
    title: "Entretiens concierges et conciergeries",
    objective: "Identifier le segment professionnel qui souffre le plus et paie potentiellement le plus.",
    targetSegment: "Segments B et C",
    testedHypothesis: "H2 / H4 / H6",
    riskAssessed: "Le segment visé pourrait préférer ses outils actuels ou ne pas assez souffrir.",
    protocol: [
      "Interroger 8 à 10 profils répartis entre indépendants et petites structures.",
      "Explorer volume de logements, charge administrative, erreurs, coordination et paiements.",
      "Comparer les douleurs par type de structure.",
    ],
    minimumParticipants: 8,
    recruitmentMode: "LinkedIn, annuaires de conciergeries, réseau local, groupes métiers",
    tools: ["Google Meet", "Sheets", "Script d'entretien"],
    prepTime: "2 h",
    executionTime: "7 h",
    estimatedCost: "0 à 30 EUR",
    collectedData: ["Nombre de logements", "Temps admin", "Outils actuels", "Douleurs critiques"],
    primaryMetrics: ["% souffrant chaque semaine", "% prêts à tester un nouvel outil"],
    secondaryMetrics: ["Budget logiciel actuel", "Type de décideur"],
    validationThreshold: ">= 70 % souffrent d'une coordination imparfaite au moins chaque semaine",
    uncertaintyThreshold: "45 % à 69 %",
    failureThreshold: "< 45 %",
    biases: ["Biais de désirabilité", "Échantillon trop digitalisé"],
    followUpAction: "Si les petites conciergeries ressortent très nettement, les traiter comme cible numéro 1.",
    deliverable: "Carte comparative Segment B vs Segment C",
  },
  {
    id: "test-3",
    number: 3,
    phase: "problem",
    title: "Observation d'un parcours réel",
    objective: "Voir les frictions réelles sans dépendre uniquement des déclarations.",
    targetSegment: "Binôme propriétaire / concierge",
    testedHypothesis: "H1 / H5",
    riskAssessed: "Le flux réel peut être moins chaotique que raconté en entretien.",
    protocol: [
      "Choisir un cas concret récent.",
      "Documenter les étapes réservation -> changement -> mission -> preuve -> paiement.",
      "Mesurer le temps, les doublons et les zones de perte d'information.",
    ],
    minimumParticipants: 1,
    recruitmentMode: "Cas réel connu de la fondatrice ou d'un contact volontaire",
    tools: ["Miro ou FigJam", "Chronométrage simple", "Capture des outils utilisés"],
    prepTime: "1 h",
    executionTime: "3 h",
    estimatedCost: "0 EUR",
    collectedData: ["Étapes", "Délai", "Outils", "Frictions", "Données obligatoires"],
    primaryMetrics: ["Nombre de transferts manuels", "Nombre de points de rupture"],
    secondaryMetrics: ["Temps total du flux", "Nombre d'outils utilisés"],
    validationThreshold: ">= 5 transferts manuels ou >= 3 points de friction critiques",
    uncertaintyThreshold: "3 à 4 transferts ou 2 frictions",
    failureThreshold: "< 3 transferts et < 2 frictions",
    biases: ["Cas atypique", "Bonne volonté exceptionnelle du participant"],
    followUpAction: "Transformer le parcours observé en démonstration MVP si la friction est nette.",
    deliverable: "Carte du flux réel et de ses ruptures",
  },
  {
    id: "test-4",
    number: 4,
    phase: "problem",
    title: "Sondage quantitatif multi-segments",
    objective: "Vérifier si les problèmes remontés sont partagés au-delà des entretiens.",
    targetSegment: "Propriétaires, concierges, petites conciergeries",
    testedHypothesis: "H1 / H2 / H4",
    riskAssessed: "Les entretiens pourraient surreprésenter des cas extrêmes.",
    protocol: [
      "Créer un sondage de 10 questions maximum.",
      "Diffuser auprès de 40 à 60 personnes qualifiées.",
      "Segmenter les résultats par profil et taille d'activité.",
    ],
    minimumParticipants: 30,
    recruitmentMode: "Groupes Facebook, LinkedIn, réseau local, mailing ciblé",
    tools: ["Tally ou Google Forms", "Sheets"],
    prepTime: "1.5 h",
    executionTime: "3 h",
    estimatedCost: "0 à 20 EUR",
    collectedData: ["Profil", "Outils", "Fréquence des problèmes", "Temps perdu", "Intérêt pour entretien"],
    primaryMetrics: ["% confirmant le problème", "Top problèmes par segment"],
    secondaryMetrics: ["Temps perdu moyen", "Taux d'intérêt pour un test"],
    validationThreshold: ">= 60 % confirment un problème récurrent",
    uncertaintyThreshold: "35 % à 59 %",
    failureThreshold: "< 35 %",
    biases: ["Auto-sélection", "Réponses superficielles"],
    followUpAction: "Si résultats dispersés, resserrer la cible avant la phase 2.",
    deliverable: "Synthèse quantitative segmentée",
  },
  {
    id: "test-5",
    number: 5,
    phase: "problem",
    title: "Test de la solution actuelle",
    objective: "Comprendre ce que les utilisateurs aiment déjà et ce qui pourrait vraiment les faire changer.",
    targetSegment: "Segments A, B, C",
    testedHypothesis: "H5 / H9",
    riskAssessed: "PlanetLS pourrait arriver contre des habitudes confortables et suffisantes.",
    protocol: [
      "Demander une démonstration ou description détaillée du système actuel.",
      "Comparer WhatsApp, Excel, calendriers, PMS, facturation et routines internes.",
      "Identifier les contournements manuels et les coûts cachés.",
    ],
    minimumParticipants: 6,
    recruitmentMode: "Participants des tests 1 et 2",
    tools: ["Entretien écran partagé", "Template d'analyse comparative"],
    prepTime: "1 h",
    executionTime: "4 h",
    estimatedCost: "0 EUR",
    collectedData: ["Stack actuelle", "Points appréciés", "Contournements", "Déclencheur de changement"],
    primaryMetrics: ["% déclarant contourner leur système actuel", "% ouverts à changer"],
    secondaryMetrics: ["Nombre d'outils empilés", "Principale objection au changement"],
    validationThreshold: ">= 50 % montrent des contournements coûteux",
    uncertaintyThreshold: "30 % à 49 %",
    failureThreshold: "< 30 %",
    biases: ["Rationalisation des outils existants"],
    followUpAction: "Adapter le MVP à ce qui remplace vraiment une douleur, pas à ce qui paraît innovant.",
    deliverable: "Benchmark réel des solutions actuelles",
  },
  {
    id: "test-6",
    number: 6,
    phase: "interest",
    title: "Landing page ciblée conciergeries",
    objective: "Mesurer l'intérêt pour une promesse centrée petites conciergeries.",
    targetSegment: "Segment C",
    testedHypothesis: "H3 / H4 / H8",
    riskAssessed: "La promesse peut rester trop large ou trop floue.",
    protocol: [
      "Créer une landing simple avec une accroche, trois bénéfices et une offre pilote.",
      "Diffuser auprès d'un trafic qualifié limité.",
      "Mesurer clics et demandes d'accès.",
    ],
    minimumParticipants: 50,
    recruitmentMode: "Prospection directe, réseau, groupes ciblés",
    tools: ["Next.js / page existante", "Formulaire simple", "UTM"],
    prepTime: "4 h",
    executionTime: "4 h",
    estimatedCost: "0 à 20 EUR",
    collectedData: ["Visites qualifiées", "Clics CTA", "Demandes de démo"],
    primaryMetrics: ["Taux de demande d'accès", "Taux de demande de démo"],
    secondaryMetrics: ["Temps passé", "Réponses libres au formulaire"],
    validationThreshold: ">= 15 % de demandes d'accès qualifiées",
    uncertaintyThreshold: "7 % à 14 %",
    failureThreshold: "< 7 %",
    biases: ["Trafic non qualifié", "Message relayé par des proches"],
    followUpAction: "Si faible résultat, retravailler d'abord la promesse avant le produit.",
    deliverable: "Landing A + premiers signaux d'intérêt",
  },
  {
    id: "test-7",
    number: 7,
    phase: "interest",
    title: "Landing page propriétaire-concierge",
    objective: "Comparer une promesse centrée sur la collaboration et le flux d'information.",
    targetSegment: "Segments A et B",
    testedHypothesis: "H3 / H5",
    riskAssessed: "La promesse de collaboration peut moins convertir que l'angle organisation pro.",
    protocol: [
      "Créer une seconde landing avec un angle propriétaire-concierge.",
      "Envoyer vers des audiences comparables.",
      "Comparer compréhension, clic et prise de rendez-vous.",
    ],
    minimumParticipants: 50,
    recruitmentMode: "Prospection directe, réseau, groupes d'hôtes et concierges",
    tools: ["Next.js / page existante", "Formulaire simple", "Suivi UTM"],
    prepTime: "4 h",
    executionTime: "4 h",
    estimatedCost: "0 à 20 EUR",
    collectedData: ["Clics CTA", "Demandes d'entretien", "Commentaires qualitatifs"],
    primaryMetrics: ["Taux d'inscription", "Taux de rendez-vous"],
    secondaryMetrics: ["Message compris au premier regard"],
    validationThreshold: "Performances proches ou supérieures à la landing conciergerie",
    uncertaintyThreshold: "Différence faible et ambiguë",
    failureThreshold: "Performances nettement inférieures",
    biases: ["Audience différente entre variantes"],
    followUpAction: "Garder uniquement l'angle qui convertit le mieux la cible prioritaire.",
    deliverable: "Comparatif Landing A / Landing B",
  },
  {
    id: "test-8",
    number: 8,
    phase: "interest",
    title: "Démonstration guidée",
    objective: "Mesurer la compréhension et la valeur perçue du parcours MVP le plus crédible.",
    targetSegment: "Segments B et C",
    testedHypothesis: "H5 / H9",
    riskAssessed: "Le produit existant peut sembler trop complexe ou pas assez clair.",
    protocol: [
      "Montrer uniquement le flux séjour -> informations voyageurs -> mission -> planning -> preuve.",
      "Limiter la démo à 15 minutes puis recueillir les réactions.",
      "Noter objections, moments de confusion et envie d'essai.",
    ],
    minimumParticipants: 5,
    recruitmentMode: "Prospects qualifiés issus des phases 1 et 2",
    tools: ["Pages PlanetLS existantes", "Visio", "Guide de démo"],
    prepTime: "2 h",
    executionTime: "3 h",
    estimatedCost: "0 EUR",
    collectedData: ["Compréhension", "Objections", "Intention d'essai"],
    primaryMetrics: ["% comprenant la valeur en moins de 5 minutes", "% demandant un essai"],
    secondaryMetrics: ["Objections dominantes", "Fonction jugée inutile"],
    validationThreshold: ">= 60 % comprennent vite et demandent un essai",
    uncertaintyThreshold: "35 % à 59 %",
    failureThreshold: "< 35 %",
    biases: ["Effet démonstration", "Fondatrice trop présente dans l'explication"],
    followUpAction: "Si confusion forte, simplifier le flux avant tout pilote.",
    deliverable: "Démo MVP + notes d'objections",
  },
  {
    id: "test-9",
    number: 9,
    phase: "interest",
    title: "Conciergerie gérée manuellement",
    objective: "Mesurer la valeur d'usage avant d'automatiser davantage.",
    targetSegment: "Segments B et C",
    testedHypothesis: "H5 / H6",
    riskAssessed: "La valeur supposée peut ne pas exister en situation réelle.",
    protocol: [
      "Choisir 1 à 2 utilisateurs pilotes.",
      "Prendre en charge manuellement une partie du flux via PlanetLS et opérations assistées.",
      "Mesurer usage, retours, frictions et temps de support.",
    ],
    minimumParticipants: 2,
    recruitmentMode: "Concierges très motivés issus des entretiens",
    tools: ["PlanetLS existant", "Support manuel", "Tableau de suivi"],
    prepTime: "2 h",
    executionTime: "8 h",
    estimatedCost: "0 à 20 EUR",
    collectedData: ["Connexions", "Tâches réalisées", "Temps de support", "Douleurs restantes"],
    primaryMetrics: ["% du flux réellement utilisé", "Temps gagné perçu"],
    secondaryMetrics: ["Temps de support par compte", "Demandes d'évolution"],
    validationThreshold: ">= 50 % du parcours principal est utilisé sur un cas réel",
    uncertaintyThreshold: "25 % à 49 %",
    failureThreshold: "< 25 %",
    biases: ["Support trop fort de la fondatrice", "Pilote trop conciliant"],
    followUpAction: "Si le support explose, réduire encore le périmètre du MVP.",
    deliverable: "Journal d'usage pilote",
  },
  {
    id: "test-10",
    number: 10,
    phase: "interest",
    title: "Offre pilote limitée",
    objective: "Tester si une offre resserrée et limitée crée un engagement plus concret.",
    targetSegment: "Segment C prioritairement",
    testedHypothesis: "H4 / H6 / H7",
    riskAssessed: "L'intérêt peut s'évaporer dès qu'il faut un cadre clair et des contreparties.",
    protocol: [
      "Proposer un pilote limité en durée, nombre de logements et support.",
      "Exiger un feedback structuré et un vrai usage.",
      "Observer qui accepte les contraintes du pilote.",
    ],
    minimumParticipants: 3,
    recruitmentMode: "Prospects les plus chauds des tests 6 à 9",
    tools: ["Document d'offre pilote", "Visio", "Suivi notion"],
    prepTime: "2 h",
    executionTime: "4 h",
    estimatedCost: "0 EUR",
    collectedData: ["Acceptation du cadre", "Nombre de logements engagés", "Usage projeté"],
    primaryMetrics: ["% acceptant le pilote", "% actifs après démarrage"],
    secondaryMetrics: ["Motifs de refus", "Conditions demandées"],
    validationThreshold: ">= 30 % des prospects chauds acceptent le pilote",
    uncertaintyThreshold: "15 % à 29 %",
    failureThreshold: "< 15 %",
    biases: ["Effet relation personnelle", "Pilote trop généreux"],
    followUpAction: "Si faible engagement, revoir la cible ou l'offre avant pricing.",
    deliverable: "Proposition pilote + réponses",
  },
  {
    id: "test-11",
    number: 11,
    phase: "willingness_to_pay",
    title: "Test de prix",
    objective: "Identifier une fourchette de prix acceptable et un format cohérent avec l'usage.",
    targetSegment: "Segments B et C",
    testedHypothesis: "H6 / H7",
    riskAssessed: "Le prix actuel à 29 EUR pourrait être trop bas, trop haut ou mal formulé.",
    protocol: [
      "Mener un test de sensibilité au prix en entretien.",
      "Présenter au moins quatre options de prix ou format.",
      "Comparer abonnement, annuel, pilote et prix par logement.",
    ],
    minimumParticipants: 8,
    recruitmentMode: "Prospects qualifiés après tests d'intérêt",
    tools: ["Entretien de vente", "Tableau de comparaison d'offres"],
    prepTime: "1.5 h",
    executionTime: "4 h",
    estimatedCost: "0 EUR",
    collectedData: ["Prix acceptable", "Prix trop bas", "Prix trop élevé", "Préférences de format"],
    primaryMetrics: ["Fourchette de prix viable", "% ouverts à payer"],
    secondaryMetrics: ["Objections au format", "Décideur final"],
    validationThreshold: "Au moins une offre recueille >= 20 % d'acceptation verbale forte",
    uncertaintyThreshold: "8 % à 19 %",
    failureThreshold: "< 8 %",
    biases: ["Réponses polies", "Négociation opportuniste"],
    followUpAction: "Ne pas geler le prix sans engagement plus fort qu'une opinion.",
    deliverable: "Carte de sensibilité au prix",
  },
  {
    id: "test-12",
    number: 12,
    phase: "willingness_to_pay",
    title: "Précommande ou dépôt d'intérêt",
    objective: "Obtenir un signal d'engagement plus fort qu'une simple inscription.",
    targetSegment: "Segment prioritaire confirmé",
    testedHypothesis: "H6 / H7 / H9",
    riskAssessed: "Les prospects peuvent être intéressés sans jamais s'engager vraiment.",
    protocol: [
      "Proposer une réservation de place pilote ou un accord écrit simple.",
      "Clarifier qu'il s'agit d'un pilote limité et réversible.",
      "Mesurer le taux d'acceptation et les blocages.",
    ],
    minimumParticipants: 5,
    recruitmentMode: "Prospects les plus engagés de la phase 2",
    tools: ["Doc d'engagement", "Email", "Calendly"],
    prepTime: "1 h",
    executionTime: "3 h",
    estimatedCost: "0 EUR",
    collectedData: ["Accords", "Refus", "Motifs", "Conditions demandées"],
    primaryMetrics: ["% d'engagement fort", "Nombre de places réservées"],
    secondaryMetrics: ["Temps de décision", "Nature des objections"],
    validationThreshold: ">= 20 % des prospects qualifiés donnent un engagement fort",
    uncertaintyThreshold: "8 % à 19 %",
    failureThreshold: "< 8 %",
    biases: ["Effet relation", "Ambiguïté juridique si cadre flou"],
    followUpAction: "Si aucun engagement fort, ne pas lancer d'offre définitive.",
    deliverable: "Registre d'engagements pilotes",
  },
  {
    id: "test-13",
    number: 13,
    phase: "willingness_to_pay",
    title: "Vente assistée",
    objective: "Mesurer la capacité réelle à convertir des prospects qualifiés en offre pilote payante ou quasi payante.",
    targetSegment: "Segment prioritaire confirmé",
    testedHypothesis: "H4 / H6 / H7",
    riskAssessed: "L'intérêt peut ne pas se transformer en décision d'achat.",
    protocol: [
      "Organiser des rendez-vous individuels de 30 à 45 minutes.",
      "Présenter problème, solution, démo, offre pilote et prix.",
      "Demander une décision ou une prochaine étape ferme.",
    ],
    minimumParticipants: 6,
    recruitmentMode: "Prospects les plus qualifiés des phases 1 et 2",
    tools: ["Visio", "Support de vente", "Suivi pipeline simple"],
    prepTime: "2 h",
    executionTime: "5 h",
    estimatedCost: "0 EUR",
    collectedData: ["Rendez-vous", "Propositions", "Accords", "Refus", "Objections prix"],
    primaryMetrics: ["Taux de closing", "Taux de refus motivés"],
    secondaryMetrics: ["Délai de décision", "Objection dominante"],
    validationThreshold: ">= 20 % acceptent une offre ou un engagement fort",
    uncertaintyThreshold: "8 % à 19 %",
    failureThreshold: "< 8 %",
    biases: ["Pression sociale en visio", "Prospects trop chauds déjà convaincus"],
    followUpAction: "Si closing faible mais douleur forte, retravailler packaging ou pricing avant de pivoter le produit.",
    deliverable: "Mini pipeline commercial Lean",
  },
];

export const interviewScripts: InterviewScript[] = [
  {
    id: "script-owner",
    audience: "Version propriétaire",
    questions: [
      "Racontez-moi la dernière fois où une information importante sur un séjour a changé au dernier moment.",
      "Comment cette information a-t-elle circulé entre vous, la concierge et les éventuels prestataires ?",
      "Quels outils avez-vous utilisés à ce moment-là ?",
      "Qu'est-ce qui a été simple et qu'est-ce qui a été pénible ?",
      "À quelle fréquence ce type de situation arrive-t-il ?",
      "Quand il y a un oubli ou une erreur, quelles conséquences cela a-t-il pour vous ?",
      "Avez-vous déjà essayé d'autres façons de vous organiser ?",
      "Qui décide aujourd'hui des outils ou méthodes utilisés avec votre concierge ?",
      "Combien êtes-vous prêt à tolérer avant de changer d'organisation ?",
      "Si vous deviez améliorer une seule chose dans votre gestion actuelle, ce serait quoi ?",
    ],
  },
  {
    id: "script-concierge",
    audience: "Version concierge ou conciergerie",
    questions: [
      "Parlez-moi du dernier séjour ou de la dernière mission qui vous a demandé trop d'allers-retours.",
      "Quelles informations vous manquent le plus souvent ou arrivent trop tard ?",
      "Quels outils utilisez-vous aujourd'hui pour gérer séjours, missions, devis et suivi ?",
      "Qu'est-ce qui vous fait perdre le plus de temps chaque semaine ?",
      "Quels types d'erreurs ou d'oublis reviennent le plus ?",
      "Combien de logements, de propriétaires et de collaborateurs devez-vous coordonner ?",
      "Qu'avez-vous déjà testé pour améliorer votre organisation ?",
      "Qui décide chez vous de prendre ou non un nouvel outil ?",
      "Quel budget logiciel ou opérationnel acceptez-vous déjà pour mieux piloter votre activité ?",
      "Qu'est-ce qui devrait être immédiatement meilleur pour que vous changiez réellement de solution ?",
    ],
  },
];

export const surveyQuestions: SurveyQuestion[] = [
  { id: "survey-1", question: "Quel est votre profil principal ?", answerFormat: "Choix unique segmenté" },
  { id: "survey-2", question: "Combien de logements gérez-vous ou possédez-vous ?", answerFormat: "Choix quantifié" },
  { id: "survey-3", question: "Comment gérez-vous aujourd'hui les séjours et missions ?", answerFormat: "Choix multiples" },
  { id: "survey-4", question: "Quels outils utilisez-vous le plus souvent ?", answerFormat: "Choix multiples" },
  { id: "survey-5", question: "À quelle fréquence rencontrez-vous des changements, oublis ou informations dispersées ?", answerFormat: "Échelle de fréquence" },
  { id: "survey-6", question: "Combien de temps cela vous fait-il perdre en moyenne ?", answerFormat: "Choix quantifié" },
  { id: "survey-7", question: "Quel est le problème principal aujourd'hui ?", answerFormat: "Choix + autre" },
  { id: "survey-8", question: "Quel est l'impact principal de ce problème ?", answerFormat: "Choix unique" },
  { id: "survey-9", question: "Êtes-vous satisfait de votre organisation actuelle ?", answerFormat: "Échelle de satisfaction" },
  { id: "survey-10", question: "Souhaitez-vous participer à un entretien ou à un test pilote ?", answerFormat: "Oui / non + contact" },
];

export const landingVariants: LandingVariant[] = [
  {
    id: "landing-1",
    audience: "Petites conciergeries",
    headline: "Centralisez logements, séjours, missions et coordination dans un seul cockpit.",
    subheadline:
      "Réduisez les oublis, gagnez du temps administratif et professionnalisez votre organisation sans multiplier les outils.",
    sections: [
      "Accroche principale",
      "Problèmes terrain récurrents",
      "3 bénéfices concrets",
      "Comment ça fonctionne",
      "Démo du parcours principal",
      "Offre pilote limitée",
      "CTA : demander un accès pilote",
    ],
  },
  {
    id: "landing-2",
    audience: "Collaboration propriétaire-concierge",
    headline: "Ne perdez plus les informations importantes entre propriétaire et concierge.",
    subheadline:
      "Regroupez séjours, consignes, changements, missions et suivi dans un espace partagé plus clair qu'un empilement de messages.",
    sections: [
      "Accroche principale",
      "Problème de dispersion de l'information",
      "Bénéfices pour les deux côtés",
      "Parcours séjour -> mission",
      "Contexte fondateur",
      "Offre pilote",
      "CTA : demander une démonstration",
    ],
  },
  {
    id: "landing-3",
    audience: "Gestion des missions",
    headline: "Transformez vos demandes et devis en missions planifiées et suivies.",
    subheadline:
      "Passez d'une coordination bricolée à un suivi plus traçable des interventions, preuves et paiements.",
    sections: [
      "Accroche principale",
      "Douleurs liées aux missions",
      "Bénéfices opérationnels",
      "Planning partagé",
      "Objections et cadre pilote",
      "CTA : réserver une place test",
    ],
  },
];

export const recruitmentMessage =
  "Bonjour, je travaille sur un outil pour mieux gérer la coordination entre propriétaires, concierges et missions en location saisonnière. Je ne cherche pas à vendre tout de suite, mais à comprendre votre organisation réelle. Accepteriez-vous un échange de 20 à 30 minutes cette semaine ?";

export const followUpMessage =
  "Bonjour, je me permets de revenir vers vous suite à mon message précédent. Je mène un court cycle de validation terrain sur les difficultés de coordination en location saisonnière. Votre retour serait très utile, même si vous n'utilisez pas PlanetLS. Auriez-vous un créneau cette semaine ?";

export const pilotOfferMessage =
  "Je propose un pilote limité PlanetLS sur une courte période, avec un périmètre clair et un accompagnement direct. L'objectif n'est pas de tout déployer, mais de vérifier si le parcours séjour -> mission -> suivi vous fait réellement gagner du temps et réduit les oublis. En échange, j'ai besoin d'un usage réel et de retours précis.";

export const validationKpis: ValidationKpi[] = [
  {
    id: "kpi-1",
    name: "Entretiens réalisés",
    definition: "Nombre d'entretiens menés avec des profils qualifiés sur la période.",
    formula: "Total entretiens complétés",
    source: "Tableau de suivi fondateur",
    currentValue: "0",
    greenThreshold: ">= 15",
    orangeThreshold: "8 à 14",
    redThreshold: "< 8",
    updateFrequency: "2 fois par semaine",
    actionIfBad: "Renforcer le recrutement et réduire le nombre de segments actifs.",
  },
  {
    id: "kpi-2",
    name: "Personnes confirmant le problème",
    definition: "Part des répondants qualifiés qui rencontrent régulièrement le problème principal.",
    formula: "Participants confirmant le problème / participants qualifiés",
    source: "Entretiens + sondage",
    currentValue: "À mesurer",
    greenThreshold: ">= 60 %",
    orangeThreshold: "35 % à 59 %",
    redThreshold: "< 35 %",
    updateFrequency: "Hebdomadaire",
    actionIfBad: "Revoir la cible ou reformuler le problème testé.",
  },
  {
    id: "kpi-3",
    name: "Inscription landing qualifiée",
    definition: "Part des visiteurs qualifiés demandant un accès, une démo ou un pilote.",
    formula: "Demandes qualifiées / visiteurs qualifiés",
    source: "Landing pages de validation",
    currentValue: "À mesurer",
    greenThreshold: ">= 15 %",
    orangeThreshold: "7 % à 14 %",
    redThreshold: "< 7 %",
    updateFrequency: "Tous les 2 jours en phase 2",
    actionIfBad: "Revoir la promesse et la cible avant de toucher au produit.",
  },
  {
    id: "kpi-4",
    name: "Activation pilote",
    definition: "Part des pilotes qui vont jusqu'au parcours principal réellement utilisé.",
    formula: "Pilotes actifs / pilotes démarrés",
    source: "Journal de pilote manuel",
    currentValue: "À mesurer",
    greenThreshold: ">= 50 %",
    orangeThreshold: "25 % à 49 %",
    redThreshold: "< 25 %",
    updateFrequency: "Hebdomadaire",
    actionIfBad: "Simplifier l'onboarding et réduire le périmètre du pilote.",
  },
  {
    id: "kpi-5",
    name: "Engagement payant ou fort",
    definition: "Part des prospects qualifiés acceptant une offre pilote, un accord ou une précommande.",
    formula: "Engagements forts / prospects qualifiés présentés",
    source: "Entretiens de vente et propositions pilotes",
    currentValue: "À mesurer",
    greenThreshold: ">= 20 %",
    orangeThreshold: "8 % à 19 %",
    redThreshold: "< 8 %",
    updateFrequency: "Fin de phase 3",
    actionIfBad: "Revoir valeur, prix ou segment avant toute industrialisation.",
  },
  {
    id: "kpi-6",
    name: "Prix moyen acceptable",
    definition: "Fourchette de prix jugée acceptable après confrontation à une offre pilote concrète.",
    formula: "Moyenne ou fourchette des réponses qualifiées",
    source: "Tests de pricing",
    currentValue: "À mesurer",
    greenThreshold: "Fourchette claire et cohérente",
    orangeThreshold: "Fourchette floue ou divergente",
    redThreshold: "Aucune base cohérente",
    updateFrequency: "Fin de phase 3",
    actionIfBad: "Tester un autre packaging avant de geler un prix.",
  },
];

export const goNoGoRules: GoNoGoRule[] = [
  {
    id: "rule-go",
    decision: "go",
    title: "GO",
    signals: [
      "Au moins 60 % des personnes qualifiées confirment un problème régulier.",
      "Au moins 40 % le classent dans leurs 3 difficultés principales.",
      "Au moins 15 % des visiteurs qualifiés demandent un accès ou une démo.",
      "Au moins 50 % des pilotes terminent le parcours principal.",
      "Au moins 20 % des prospects qualifiés acceptent une offre ou un engagement fort.",
    ],
    nextMove: "Lancer un pilote resserré sur le segment gagnant et formaliser une offre testée 30 jours.",
  },
  {
    id: "rule-test-more",
    decision: "test_more",
    title: "TEST MORE",
    signals: [
      "Le problème existe mais la cible ou la promesse restent floues.",
      "L'intérêt est réel mais l'usage reste faible.",
      "Le prix bloque sans invalider la valeur.",
      "Les résultats diffèrent fortement selon les segments.",
    ],
    nextMove: "Resserrer un segment, une promesse et un test complémentaire au lieu d'élargir le produit.",
  },
  {
    id: "rule-pivot",
    decision: "pivot",
    title: "PIVOT / NO-GO",
    signals: [
      "Moins de 30 à 35 % rencontrent réellement le problème.",
      "Le problème est jugé secondaire ou les outils actuels suffisent.",
      "Les pilotes n'utilisent pas le produit malgré l'accompagnement.",
      "Personne n'accepte un engagement ou un paiement pilote.",
      "La charge de support dépasse la valeur créée pour une fondatrice seule.",
    ],
    nextMove: "Réduire radicalement le périmètre, changer de segment ou mettre en pause avant d'investir davantage.",
  },
];

export const integrationRecommendations: IntegrationRecommendation[] = [
  {
    id: "integration-1",
    title: "Composants à réutiliser",
    items: reusableComponents,
  },
  {
    id: "integration-2",
    title: "Composants légers à créer",
    items: [
      "LeanValidationDashboard",
      "ValidationExperimentCard",
      "ValidationKpiCard",
      "GoNoGoDecisionPanel",
      "ValidationLearningLog",
    ],
  },
  {
    id: "integration-3",
    title: "Données à suivre",
    items: [
      "Hypothèses critiques",
      "Tests planifiés et complétés",
      "Participants et preuves",
      "Décisions GO / TEST MORE / PIVOT",
    ],
  },
  {
    id: "integration-4",
    title: "Migrations éventuelles",
    items: [
      "Aucune migration immédiate recommandée",
      "Envisager plus tard une persistance `validation_hypotheses`, `validation_experiments`, `validation_evidence` seulement si la routine devient réelle",
    ],
  },
];

export const immediateActionGroups: ImmediateActionGroup[] = [
  {
    id: "actions-week",
    title: "Les 3 actions à réaliser cette semaine",
    items: [
      "Préparer les scripts d'entretien et la liste de 20 à 30 contacts qualifiés.",
      "Conduire les premiers entretiens concierges / petites conciergeries.",
      "Documenter un parcours réel complet réservation -> mission -> preuve -> paiement.",
    ],
  },
  {
    id: "actions-stop",
    title: "Les 3 développements à ne pas commencer",
    items: [
      "Nouvelle IA premium non demandée par le terrain",
      "Marketplace nationale ou moteur de commission complexe",
      "Refonte majeure de dashboards avant preuve de valeur commerciale",
    ],
  },
  {
    id: "actions-contacts",
    title: "Les 5 profils à contacter en premier",
    items: [
      "2 petites conciergeries gérant plusieurs logements",
      "2 concierges indépendants multi-propriétaires",
      "1 propriétaire collaborant déjà avec une concierge",
      "1 prestataire récurrent intervenant pour plusieurs logements",
      "1 contact métier local capable d'ouvrir vers d'autres prospects",
    ],
  },
  {
    id: "actions-first-test",
    title: "Le premier test à lancer",
    items: ["Test 2 - Entretiens concierges et conciergeries"],
  },
  {
    id: "actions-proof",
    title: "La preuve principale à rechercher",
    items: [
      "Un professionnel qui souffre du problème chaque semaine, comprend la promesse rapidement et accepte un pilote cadré avec un engagement plus fort qu'une simple curiosité.",
    ],
  },
];

export const totalEstimatedBudget = "150 à 240 EUR";
export const totalEstimatedTime = "38 à 48 heures sur 30 jours";
export const nextDecisions = [
  "Quel segment devient officiellement prioritaire après la phase 1 ?",
  "Quel parcours minimum forme le MVP réel après la phase 2 ?",
  "Quel packaging et quel prix méritent un pilote payant après la phase 3 ?",
];
