var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/pricing/strategy-scenarios/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__6324b65a._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_b7faa18d._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_da86c597._.js")
R.c("server/chunks/node_modules_42103433._.js")
R.c("server/chunks/ce889_server_app_api_pricing_strategy-scenarios_[id]_route_actions_f806fd00.js")
R.m(71196)
module.exports=R.m(71196).exports
