var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/concierge/stays/route.js")
R.c("server/chunks/[root-of-the-server]__472a5e98._.js")
R.c("server/chunks/node_modules_b7faa18d._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_71a6939c.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_42103433._.js")
R.c("server/chunks/_da86c597._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_next-internal_server_app_api_concierge_stays_route_actions_0b84788b.js")
R.m(554059)
module.exports=R.m(554059).exports
