var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/provider/clients/route.js")
R.c("server/chunks/[root-of-the-server]__1ed0cb28._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_b7faa18d._.js")
R.c("server/chunks/_da86c597._.js")
R.c("server/chunks/node_modules_42103433._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_next-internal_server_app_api_provider_clients_route_actions_10c1977f.js")
R.m(110259)
module.exports=R.m(110259).exports
