var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/admin/conciergeries/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__b9d71457._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b63a0e1._.js")
R.c("server/chunks/ssr/_0d6682de._.js")
R.c("server/chunks/ssr/[root-of-the-server]__3224e5a4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1690ee0d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_2df23979._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/src_app_e491dc8a._.js")
R.c("server/chunks/ssr/src_app_error_tsx_ef715cc8._.js")
R.c("server/chunks/ssr/_61b58078._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_dashboard_layout_tsx_ebf7678c._.js")
R.c("server/chunks/ssr/_next-internal_server_app_dashboard_admin_conciergeries_page_actions_ba18f815.js")
R.m(56761)
module.exports=R.m(56761).exports
