var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/housing/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__c23fb7be._.js")
R.c("server/chunks/node_modules_b7faa18d._.js")
R.c("server/chunks/src_types_housing_ts_d65fbbb5._.js")
R.c("server/chunks/_da86c597._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_42103433._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_next-internal_server_app_api_housing_[id]_route_actions_d9b51434.js")
R.m(994156)
module.exports=R.m(994156).exports
