var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/services/pricing-packages/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__4ab3d3b4._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_b7faa18d._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_da86c597._.js")
R.c("server/chunks/node_modules_42103433._.js")
R.c("server/chunks/ce889_server_app_api_services_pricing-packages_[id]_route_actions_1e9f4962.js")
R.m(410212)
module.exports=R.m(410212).exports
