import type { BusinessRisk } from "./riskTypes";

export const businessRisks: BusinessRisk[] = [
  {
    id: "R-MAR-001",
    priority: "critique",
    category: "marche",
    title: "Positionnement trop large entre SaaS, marketplace et réseau",
    description:
      "PlanetLS combine encore trois moteurs économiques difficiles à exécuter en même temps, ce qui complique la compréhension de l'offre et la priorisation de la roadmap.",
    cause: "Vision large avant validation d'un noyau de valeur unique.",
    affectedProfiles: ["conciergeries", "proprietaires", "administrateurs"],
    probability: "elevee",
    impact: "eleve",
    horizon: "immediat",
    mitigation: "Focaliser le message, la vente et le produit sur Conciergerie Pro comme moteur principal.",
    warningSignals: [
      "Objections de compréhension de l'offre en entretien commercial",
      "Taux de closing faible malgré des démos positives",
    ],
    owner: "Fondatrice / Produit",
    deadline: "30 jours",
    status: "identifie",
  },
  {
    id: "R-COM-002",
    priority: "critique",
    category: "commercial",
    title: "Modèle tarifaire non validé sur données réelles",
    description:
      "Le projet dispose d'hypothèses de prix et d'une offre Stripe existante, mais le modèle économique principal n'est pas encore validé sur une offre stable et comparable.",
    cause: "Absence de test commercial structuré sur une offre unique pendant plusieurs semaines.",
    affectedProfiles: ["conciergeries", "administrateurs"],
    probability: "elevee",
    impact: "eleve",
    horizon: "immediat",
    mitigation: "Geler une seule offre payante pendant 60 jours et mesurer conversion, activation et rétention.",
    warningSignals: [
      "Discounts fréquents pour conclure",
      "Objections prix récurrentes sans objection produit claire",
    ],
    owner: "Fondatrice / Pricing",
    deadline: "15 jours",
    status: "identifie",
  },
  {
    id: "R-MKP-003",
    priority: "critique",
    category: "marketplace",
    title: "Liquidité locale insuffisante",
    description:
      "La marketplace peut échouer si une zone ne contient pas assez de conciergeries, d'artisans ou de missions pour produire une expérience utile et rapide.",
    cause: "Problème de démarrage à froid et densité locale non prouvée.",
    affectedProfiles: ["proprietaires", "conciergeries", "artisans", "prestataires"],
    probability: "elevee",
    impact: "eleve",
    horizon: "trois_mois",
    mitigation: "Concentrer l'acquisition et l'offre sur une zone pilote avant toute expansion géographique.",
    warningSignals: [
      "Temps de réponse trop long sur les demandes",
      "Faible nombre de prestataires disponibles dans une zone",
    ],
    owner: "GTM / Operations",
    deadline: "90 jours",
    status: "identifie",
  },
  {
    id: "R-MKP-004",
    priority: "critique",
    category: "marketplace",
    title: "Désintermédiation après la première mise en relation",
    description:
      "Une fois le premier contact établi, propriétaires, conciergeries et prestataires peuvent poursuivre hors plateforme, détruisant les revenus de commission et les données de valeur.",
    cause: "Valeur post-match encore insuffisamment incontournable.",
    affectedProfiles: ["proprietaires", "conciergeries", "artisans", "prestataires"],
    probability: "elevee",
    impact: "eleve",
    horizon: "trois_mois",
    mitigation: "Renforcer les preuves, le suivi, les paiements et les avantages à rester dans PlanetLS.",
    warningSignals: [
      "Missions créées sans paiement ou facture visible dans PlanetLS",
      "Baisse d'usage messagerie après première connexion",
    ],
    owner: "Produit / Operations",
    deadline: "90 jours",
    status: "identifie",
  },
  {
    id: "R-FIN-005",
    priority: "critique",
    category: "financier",
    title: "Absence de vérité économique sur CAC, LTV et churn",
    description:
      "Les hypothèses de rentabilité restent fragiles tant que CAC, rétention, churn et coût d'onboarding ne sont pas mesurés sur cohortes réelles.",
    cause: "Traction payante encore insuffisante et instrumentation business incomplète.",
    affectedProfiles: ["administrateurs"],
    probability: "elevee",
    impact: "eleve",
    horizon: "immediat",
    mitigation: "Créer un tableau de suivi cohortes et lier chaque offre testée à ses indicateurs économiques.",
    warningSignals: [
      "Réunions de pilotage basées sur hypothèses plutôt que données observées",
      "Incapacité à justifier un prix ou une marge avec des chiffres réels",
    ],
    owner: "Finance / Data",
    deadline: "30 jours",
    status: "identifie",
  },
  {
    id: "R-TEC-006",
    priority: "prioritaire",
    category: "technologique",
    title: "Dépendance forte aux metadata et aux fallbacks",
    description:
      "Plusieurs parcours coeur s'appuient encore sur des lectures metadata, des compatibilités legacy et des sélections souples, ce qui complique l'évolutivité.",
    cause: "Objets métier canoniques encore en consolidation et schéma distant incomplet.",
    affectedProfiles: ["administrateurs", "conciergeries", "proprietaires"],
    probability: "elevee",
    impact: "moyen",
    horizon: "trois_mois",
    mitigation: "Canoniser les objets métier critiques et réduire progressivement les fallback legacy.",
    warningSignals: [
      "Régressions lors de modifications de schéma",
      "Temps de debug élevé sur les routes métier",
    ],
    owner: "Tech",
    deadline: "3 mois",
    status: "a_analyser",
  },
  {
    id: "R-OPE-007",
    priority: "prioritaire",
    category: "operationnel",
    title: "Dépendance à la fondatrice pour la vente, le support et l'arbitrage",
    description:
      "Le projet semble encore centraliser beaucoup de fonctions critiques sur une personne, ce qui limite la vitesse et augmente le risque d'engorgement.",
    cause: "Équipe réduite et processus peu délégués.",
    affectedProfiles: ["administrateurs", "conciergeries"],
    probability: "elevee",
    impact: "moyen",
    horizon: "trois_mois",
    mitigation: "Documenter les process, réduire les exceptions et déléguer les boucles répétitives.",
    warningSignals: [
      "Retards de réponse support ou commercial",
      "Blocages de décision faute de disponibilité fondatrice",
    ],
    owner: "Fondatrice / Operations",
    deadline: "3 mois",
    status: "identifie",
  },
  {
    id: "R-JUR-008",
    priority: "prioritaire",
    category: "juridique",
    title: "Responsabilités insuffisamment cadrées en cas de litige ou dommage",
    description:
      "Le rôle exact de PlanetLS comme plateforme d'intermédiation, de transaction et de conservation de preuves doit être mieux borné juridiquement.",
    cause: "Complexité du mélange marketplace, paiement et exécution terrain.",
    affectedProfiles: ["proprietaires", "conciergeries", "artisans", "administrateurs"],
    probability: "moyenne",
    impact: "eleve",
    horizon: "trois_mois",
    mitigation: "Faire revoir CGU, CGV, responsabilités, assurance et clauses litiges par un conseil spécialisé.",
    warningSignals: [
      "Litiges sans procédure standard",
      "Questions récurrentes sur qui porte la responsabilité du dommage",
    ],
    owner: "Juridique / Fondatrice",
    deadline: "Avant lancement commercial large",
    status: "a_analyser",
  },
  {
    id: "R-COM-009",
    priority: "prioritaire",
    category: "commercial",
    title: "Faible adoption des équipes terrain",
    description:
      "Si les intervenants terrain n'utilisent pas régulièrement PlanetLS, la preuve d'exécution, la coordination et la valeur de l'abonnement chutent.",
    cause: "Usage mobile exigeant et habitudes de travail hors outil.",
    affectedProfiles: ["equipe", "conciergeries", "artisans"],
    probability: "moyenne",
    impact: "moyen",
    horizon: "trois_mois",
    mitigation: "Simplifier les parcours mobiles et mesurer le taux d'utilisation par mission.",
    warningSignals: [
      "Missions clôturées sans preuves dans la plateforme",
      "Utilisateurs terrain inactifs après onboarding",
    ],
    owner: "Produit / UX",
    deadline: "3 mois",
    status: "identifie",
  },
  {
    id: "R-FIN-010",
    priority: "surveiller",
    category: "financier",
    title: "Croissance non rentable à cause du support et de l'accompagnement",
    description:
      "Le modèle hybride peut sembler sain commercialement mais devenir peu rentable si le temps humain par compte reste trop élevé.",
    cause: "Onboarding, support et opérations trop manuels.",
    affectedProfiles: ["conciergeries", "administrateurs"],
    probability: "moyenne",
    impact: "moyen",
    horizon: "six_mois",
    mitigation: "Mesurer le coût d'onboarding et standardiser les parcours répétitifs.",
    warningSignals: [
      "Temps d'accompagnement croissant par client",
      "Marge brute inférieure aux attentes sur les premiers comptes payants",
    ],
    owner: "Finance / Operations",
    deadline: "6 mois",
    status: "a_analyser",
  },
  {
    id: "R-IA-011",
    priority: "surveiller",
    category: "ia",
    title: "Fonctionnalités IA coûteuses mais peu utiles",
    description:
      "Des modules IA peuvent générer des coûts, des attentes et des risques de confiance sans contribuer au noyau de valeur du produit.",
    cause: "Attrait du narratif IA avant preuve d'usage et ROI utilisateur.",
    affectedProfiles: ["conciergeries", "proprietaires", "administrateurs"],
    probability: "moyenne",
    impact: "moyen",
    horizon: "six_mois",
    mitigation: "Garder l'IA en option, superviser humainement et mesurer son usage réel avant extension.",
    warningSignals: [
      "Fonctionnalités IA peu utilisées",
      "Coût variable IA en hausse sans impact visible sur conversion ou rétention",
    ],
    owner: "Produit / IA",
    deadline: "6 mois",
    status: "identifie",
  },
  {
    id: "R-MAR-012",
    priority: "acceptable",
    category: "marche",
    title: "Expansion européenne abordée trop tôt",
    description:
      "L'Europe peut devenir un axe de croissance, mais le risque actuel est surtout de distraire l'équipe avant validation locale en France.",
    cause: "Tentation de raconter un grand TAM avant preuve locale.",
    affectedProfiles: ["administrateurs"],
    probability: "moyenne",
    impact: "faible",
    horizon: "douze_mois",
    mitigation: "Reporter tout plan Europe tant qu'une zone pilote française n'est pas économiquement prouvée.",
    warningSignals: [
      "Temps de roadmap consommé sur des sujets non locaux",
      "Slides ou discours trop centrés sur l'Europe sans traction France",
    ],
    owner: "Fondatrice / Strategie",
    deadline: "12 mois",
    status: "identifie",
  },
];
