var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/urgent-missions/[id]/accept/route.js")
R.c("server/chunks/[root-of-the-server]__69fc6a6a._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_b7faa18d._.js")
R.c("server/chunks/_da86c597._.js")
R.c("server/chunks/node_modules_42103433._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_next-internal_server_app_api_urgent-missions_[id]_accept_route_actions_31aa62b8.js")
R.m(99715)
module.exports=R.m(99715).exports
