var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/prompt-library/route.js")
R.c("server/chunks/[root-of-the-server]__06b8ae46._.js")
R.c("server/chunks/node_modules_b7faa18d._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_a5bf3934.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/_da86c597._.js")
R.c("server/chunks/node_modules_42103433._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_prompt-library_route_actions_b04ff0e6.js")
R.m(649960)
module.exports=R.m(649960).exports
