var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/concierge/optimized-routes/optimize/route.js")
R.c("server/chunks/[root-of-the-server]__efba1dbd._.js")
R.c("server/chunks/node_modules_b7faa18d._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_caec1156.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/_da86c597._.js")
R.c("server/chunks/node_modules_42103433._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/ce889_server_app_api_concierge_optimized-routes_optimize_route_actions_000ea969.js")
R.m(431424)
module.exports=R.m(431424).exports
