import type {
  PricingDecisionLogEntry,
  PricingOffer,
  PricingProfile,
  PricingStrategy,
} from "./types";

export const PRICING_PROFILES: PricingProfile[] = [
  {
    id: "owners",
    label: "Propriétaires",
    description: "Clients finaux, investisseurs et propriétaires multi-biens.",
  },
  {
    id: "concierges",
    label: "Concierges et conciergeries",
    description: "Cible business prioritaire pour le cockpit d'exploitation PlanetLS.",
  },
  {
    id: "providers",
    label: "Artisans et prestataires",
    description: "Intervenants terrain, partenaires récurrents et réseau local.",
  },
  {
    id: "partners",
    label: "Réseaux et partenaires",
    description: "Structures multisites, franchises ou comptes Enterprise futurs.",
  },
];

export const EXISTING_PRODUCTION_OFFERS: PricingOffer[] = [
  {
    id: "concierge-pro-existing",
    name: "Conciergerie Pro",
    targetProfileIds: ["concierges"],
    description: "Offre réelle déjà branchée au checkout Stripe, conservée comme référence de production.",
    monthlyPrice: 29,
    annualPrice: null,
    annualDiscountRate: null,
    trialDays: null,
    includedProperties: null,
    includedUsers: null,
    includedMissions: null,
    commissionRate: null,
    modules: ["Abonnement mensuel Concierge PRO"],
    features: [
      "Checkout Stripe existant",
      "Synchronisation du statut concierge_pro",
      "Suivi de l'historique de synchronisation",
    ],
    limits: [
      "Aucune modification Stripe dans ce module",
      "Pas d'activation automatique depuis une simulation",
      "Offre non encore validée commercialement comme modèle final",
    ],
    badge: "Offre existante",
    displayOrder: 1,
    status: "active",
    source: "real",
    isExistingStripeOffer: true,
    isLockedProduction: true,
    stripePlanCode: "concierge_pro_monthly",
  },
];

export const PRICING_STRATEGIES: PricingStrategy[] = [
  {
    id: "strategy-a",
    name: "Stratégie A - Tarification par profil",
    type: "profile_based",
    description: "Une gamme distincte par métier, avec des promesses adaptées au contexte de chaque profil.",
    targetProfileIds: ["owners", "concierges", "providers"],
    targetRevenue: "MRR segmenté par métier",
    complexityLabel: "Élevée",
    comprehensionLabel: "Moyenne",
    implementationDelay: "Moyen terme",
    riskLabel: "Risque de complexité commerciale",
    status: "under_review",
    priorityLabel: "À analyser",
    advantages: [
      "Valeur plus précise par profil",
      "Meilleure capacité de monétisation ciblée",
      "Storytelling commercial plus spécifique",
    ],
    risks: [
      "Catalogue d'offres plus large à maintenir",
      "Risque de confusion sur la page tarifaire",
      "Pilotage Stripe futur plus complexe",
    ],
    offers: [],
    scenarios: [],
  },
  {
    id: "strategy-b",
    name: "Stratégie B - Tarification par niveau",
    type: "tier_based",
    description: "Une même gamme Gratuit / Essentiel / Pro / Business / Enterprise pour tous les profils.",
    targetProfileIds: ["owners", "concierges", "providers"],
    targetRevenue: "MRR lisible et standardisé",
    complexityLabel: "Moyenne",
    comprehensionLabel: "Forte",
    implementationDelay: "Court à moyen terme",
    riskLabel: "Risque d'inadéquation métier",
    status: "under_review",
    priorityLabel: "À analyser",
    advantages: [
      "Page tarifaire plus simple",
      "Montée en gamme facile à lire",
      "Maintenance commerciale plus légère",
    ],
    risks: [
      "Découpage parfois artificiel entre métiers",
      "Valeur perçue inégale selon les profils",
      "Difficulté à justifier le même palier partout",
    ],
    offers: [],
    scenarios: [],
  },
  {
    id: "strategy-c",
    name: "Stratégie C - Modèle hybride profil + niveau",
    type: "hybrid",
    description: "Chaque profil garde une gamme adaptée, mais avec une logique de niveaux cohérente et extensible.",
    targetProfileIds: ["owners", "concierges", "providers"],
    targetRevenue: "MRR structuré + upsell modulable",
    complexityLabel: "Élevée",
    comprehensionLabel: "Bonne si bien cadrée",
    implementationDelay: "Moyen terme",
    riskLabel: "Risque de configuration et de gouvernance",
    status: "simulating",
    priorityLabel: "Hypothèse prioritaire",
    advantages: [
      "Prix et valeur mieux alignés par métier",
      "Progression naturelle vers le payant",
      "Base saine pour ajouter ensuite des modules",
    ],
    risks: [
      "Plus de règles métier à maintenir",
      "Besoin d'une communication très claire",
      "Montée en complexité produit plus rapide",
    ],
    offers: [],
    scenarios: [],
  },
  {
    id: "strategy-d",
    name: "Stratégie D - Abonnement + commission",
    type: "subscription_commission",
    description: "Un socle SaaS mensuel combiné à une commission liée aux flux réellement intermédiés.",
    targetProfileIds: ["concierges", "providers"],
    targetRevenue: "MRR + revenu transactionnel",
    complexityLabel: "Élevée",
    comprehensionLabel: "Moyenne",
    implementationDelay: "Moyen terme",
    riskLabel: "Risque juridique et opérationnel",
    status: "under_review",
    priorityLabel: "À comparer",
    advantages: [
      "Diversification des revenus",
      "Possibilité d'entrée gratuite ou faible",
      "Alignement partiel sur l'usage",
    ],
    risks: [
      "Désintermédiation potentielle",
      "Prévision financière moins stable",
      "Gestion des remboursements et paiements plus délicate",
    ],
    offers: [],
    scenarios: [],
  },
  {
    id: "strategy-e",
    name: "Stratégie E - Prix au nombre de logements",
    type: "per_property",
    description: "Tarification proportionnelle au portefeuille géré, surtout pertinente pour les conciergeries.",
    targetProfileIds: ["concierges"],
    targetRevenue: "MRR corrélé au portefeuille",
    complexityLabel: "Moyenne",
    comprehensionLabel: "Bonne",
    implementationDelay: "Court à moyen terme",
    riskLabel: "Risque d'effet de seuil",
    status: "under_review",
    priorityLabel: "À analyser",
    advantages: [
      "Prix proportionnel à la valeur perçue",
      "Référence connue sur le marché logiciel locatif",
      "Croissance de revenu alignée sur la croissance client",
    ],
    risks: [
      "Impression de pénaliser la croissance",
      "Besoin de comptage fiable",
      "Moins confortable pour les toutes petites structures",
    ],
    offers: [],
    scenarios: [],
  },
  {
    id: "strategy-f",
    name: "Stratégie F - Prix par utilisateur",
    type: "per_user",
    description: "Le prix dépend du nombre de collaborateurs impliqués dans l'exploitation.",
    targetProfileIds: ["concierges", "partners"],
    targetRevenue: "MRR équipe et multisite",
    complexityLabel: "Moyenne",
    comprehensionLabel: "Bonne",
    implementationDelay: "Moyen terme",
    riskLabel: "Risque de frein à l'adoption équipe",
    status: "idea",
    priorityLabel: "Idée",
    advantages: [
      "Logique simple à vendre aux structures organisées",
      "Compatible avec une offre Enterprise future",
      "Lisibilité pour les comptes multisites",
    ],
    risks: [
      "Décorrélation possible avec la valeur réelle",
      "Peut freiner l'ajout de collaborateurs",
      "Moins pertinent pour les indépendants",
    ],
    offers: [],
    scenarios: [],
  },
  {
    id: "strategy-g",
    name: "Stratégie G - Freemium",
    type: "freemium",
    description: "Une offre gratuite d'entrée dans l'écosystème, avec montée progressive vers les fonctions premium.",
    targetProfileIds: ["owners", "concierges", "providers"],
    targetRevenue: "Acquisition puis conversion",
    complexityLabel: "Élevée",
    comprehensionLabel: "Forte",
    implementationDelay: "Moyen à long terme",
    riskLabel: "Risque de faible conversion",
    status: "idea",
    priorityLabel: "Idée",
    advantages: [
      "Barrière d'entrée basse",
      "Peut nourrir la base et les effets réseau",
      "Supporte une stratégie de test progressif",
    ],
    risks: [
      "Coût des comptes gratuits",
      "Support non rentable si l'offre est trop large",
      "Difficulté à fixer la bonne frontière premium",
    ],
    offers: [],
    scenarios: [],
  },
  {
    id: "strategy-h",
    name: "Stratégie H - Modules complémentaires",
    type: "addons",
    description: "Un socle d'abonnement plus des briques optionnelles : IA, reporting, automatisations, API, etc.",
    targetProfileIds: ["concierges", "owners", "partners"],
    targetRevenue: "MRR socle + revenus additionnels",
    complexityLabel: "Élevée",
    comprehensionLabel: "Moyenne",
    implementationDelay: "Moyen à long terme",
    riskLabel: "Risque de catalogue trop complexe",
    status: "under_review",
    priorityLabel: "À cadrer",
    advantages: [
      "Monétisation fine de la valeur avancée",
      "Possibilité de vendre sans alourdir le socle",
      "Bonne logique pour la roadmap future",
    ],
    risks: [
      "Complexité marketing et produit",
      "Support et pricing plus exigeants",
      "Nécessite des usages déjà bien validés",
    ],
    offers: [],
    scenarios: [],
  },
  {
    id: "strategy-i",
    name: "Stratégie I - Paiement à l'usage",
    type: "usage_based",
    description: "Facturation selon des événements à coût variable : mission, devis, SMS, analyse IA, etc.",
    targetProfileIds: ["concierges", "providers"],
    targetRevenue: "Usage et coûts variables",
    complexityLabel: "Élevée",
    comprehensionLabel: "Moyenne",
    implementationDelay: "Long terme",
    riskLabel: "Risque de lisibilité et de friction",
    status: "idea",
    priorityLabel: "Option complémentaire",
    advantages: [
      "Bonne logique pour les coûts réellement variables",
      "Peut compléter un socle sans tout renverser",
      "Permet de protéger certaines briques coûteuses",
    ],
    risks: [
      "Facture moins prévisible pour le client",
      "Expérience plus difficile à expliquer",
      "Instrumentation produit plus complexe",
    ],
    offers: [],
    scenarios: [],
  },
  {
    id: "strategy-j",
    name: "Stratégie J - Enterprise sur devis",
    type: "enterprise",
    description: "Offre dédiée aux réseaux, franchises, multisites ou grands comptes avec besoins avancés.",
    targetProfileIds: ["partners", "concierges"],
    targetRevenue: "Deals sur mesure à panier élevé",
    complexityLabel: "Moyenne à élevée",
    comprehensionLabel: "Bonne",
    implementationDelay: "Plus tard",
    riskLabel: "Risque de dispersion précoce",
    status: "idea",
    priorityLabel: "Évolution future",
    advantages: [
      "Panier potentiel élevé",
      "Adapté aux demandes spécifiques",
      "Porte d'entrée pour API, marque blanche et SLA",
    ],
    risks: [
      "Vente plus longue",
      "Risque d'alourdir le produit trop tôt",
      "Peu compatible avec la phase actuelle de validation",
    ],
    offers: [],
    scenarios: [],
  },
];

export const PRICING_DECISION_LOG: PricingDecisionLogEntry[] = [
  {
    id: "decision-1",
    date: "2026-08-03",
    decision: "Conserver Conciergerie Pro comme offre de production visible mais verrouillée.",
    strategyType: "shared",
    rationale: "Le parcours d'abonnement Stripe existe déjà et sert de vérité opérationnelle minimale.",
    consequence: "Le module de pilotage peut comparer des hypothèses sans toucher à la production.",
    nextReview: "2026-08-20",
    status: "tracked",
  },
  {
    id: "decision-2",
    date: "2026-08-06",
    decision: "Traiter le modèle hybride profil + niveau comme hypothèse prioritaire, sans décision finale.",
    strategyType: "hybrid",
    rationale: "C'est l'option la plus cohérente avec la diversité des profils et la montée en gamme future.",
    consequence: "Les futures simulations doivent d'abord comparer ce scénario aux variantes plus simples.",
    nextReview: "2026-08-25",
    status: "open",
  },
];
