var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/owner-invitations/[id]/resend/route.js")
R.c("server/chunks/src_types_housing_ts_d65fbbb5._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/[root-of-the-server]__b3680edb._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_da86c597._.js")
R.c("server/chunks/node_modules_42103433._.js")
R.c("server/chunks/node_modules_b7faa18d._.js")
R.c("server/chunks/ce889_server_app_api_owner-invitations_[id]_resend_route_actions_7a527d29.js")
R.m(381760)
module.exports=R.m(381760).exports
