var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/service-request-recipients/[id]/prepare-quote/route.js")
R.c("server/chunks/[root-of-the-server]__c90cdd24._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_f465747e.js")
R.c("server/chunks/_da86c597._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_42103433._.js")
R.c("server/chunks/node_modules_b7faa18d._.js")
R.c("server/chunks/bec2d_app_api_service-request-recipients_[id]_prepare-quote_route_actions_c1f7e7f2.js")
R.m(541878)
module.exports=R.m(541878).exports
