var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/reservations/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__7649b418._.js")
R.c("server/chunks/node_modules_b7faa18d._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_ba4d2b81.js")
R.c("server/chunks/_da86c597._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_42103433._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/_next-internal_server_app_api_reservations_[id]_route_actions_9ba5d2c1.js")
R.m(805546)
module.exports=R.m(805546).exports
