var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/concierge/team/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__5d6096a4._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_b7faa18d._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_da86c597._.js")
R.c("server/chunks/node_modules_42103433._.js")
R.c("server/chunks/_next-internal_server_app_api_concierge_team_[id]_route_actions_8f501f0a.js")
R.m(960694)
module.exports=R.m(960694).exports
