var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/quotes/from-mission/route.js")
R.c("server/chunks/[root-of-the-server]__50badb3c._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_b7faa18d._.js")
R.c("server/chunks/_da86c597._.js")
R.c("server/chunks/node_modules_42103433._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/_next-internal_server_app_api_quotes_from-mission_route_actions_ca9f8c74.js")
R.m(945690)
module.exports=R.m(945690).exports
