var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/services/service_pricing/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__460d09a5._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_b7faa18d._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_da86c597._.js")
R.c("server/chunks/node_modules_42103433._.js")
R.c("server/chunks/ce889_server_app_api_services_service_pricing_[id]_route_actions_880f396e.js")
R.m(300199)
module.exports=R.m(300199).exports
