var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/inspections/[id]/route.js")
R.c("server/chunks/[root-of-the-server]__3633b6b9._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_b7faa18d._.js")
R.c("server/chunks/node_modules_42103433._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/_da86c597._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_next-internal_server_app_api_inspections_[id]_route_actions_3fb29d96.js")
R.m(479407)
module.exports=R.m(479407).exports
