var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/concierge/reservations/route.js")
R.c("server/chunks/[root-of-the-server]__d1145425._.js")
R.c("server/chunks/node_modules_b7faa18d._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_7dd9915a.js")
R.c("server/chunks/_da86c597._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_42103433._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_next-internal_server_app_api_concierge_reservations_route_actions_1b18c222.js")
R.m(75119)
module.exports=R.m(75119).exports
