var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/concierge/match-owner-requests/route.js")
R.c("server/chunks/[root-of-the-server]__c8b71205._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_b7faa18d._.js")
R.c("server/chunks/_da86c597._.js")
R.c("server/chunks/node_modules_42103433._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/ce889_server_app_api_concierge_match-owner-requests_route_actions_20b1ebf0.js")
R.m(325489)
module.exports=R.m(325489).exports
