-- Decoration AI reports generated by concierges for owner-facing proposals
-- Date: 2026-07-18

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.decoration_ai_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  concierge_profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  owner_profile_id UUID NULL REFERENCES public.profiles(id) ON DELETE SET NULL,
  owner_name TEXT,
  owner_email TEXT,
  property_name TEXT,
  room_name TEXT NOT NULL,
  housing_type TEXT NOT NULL,
  style TEXT NOT NULL,
  goal TEXT NOT NULL,
  budget_requested NUMERIC(12, 2) NOT NULL DEFAULT 0,
  budget_estimated NUMERIC(12, 2) NOT NULL DEFAULT 0,
  report JSONB NOT NULL DEFAULT '{}'::jsonb,
  image_prompt TEXT,
  sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_decoration_ai_reports_concierge_created_at
  ON public.decoration_ai_reports(concierge_profile_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_decoration_ai_reports_owner_created_at
  ON public.decoration_ai_reports(owner_profile_id, created_at DESC)
  WHERE owner_profile_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_decoration_ai_reports_style_created_at
  ON public.decoration_ai_reports(style, created_at DESC);

ALTER TABLE public.decoration_ai_reports ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS decoration_ai_reports_select_participants ON public.decoration_ai_reports;
CREATE POLICY decoration_ai_reports_select_participants
  ON public.decoration_ai_reports
  FOR SELECT
  USING (
    auth.role() = 'service_role'
    OR auth.uid() = concierge_profile_id
    OR auth.uid() = owner_profile_id
  );

DROP POLICY IF EXISTS decoration_ai_reports_insert_concierge ON public.decoration_ai_reports;
CREATE POLICY decoration_ai_reports_insert_concierge
  ON public.decoration_ai_reports
  FOR INSERT
  WITH CHECK (
    auth.role() = 'service_role'
    OR auth.uid() = concierge_profile_id
  );

DROP POLICY IF EXISTS decoration_ai_reports_update_concierge ON public.decoration_ai_reports;
CREATE POLICY decoration_ai_reports_update_concierge
  ON public.decoration_ai_reports
  FOR UPDATE
  USING (
    auth.role() = 'service_role'
    OR auth.uid() = concierge_profile_id
  )
  WITH CHECK (
    auth.role() = 'service_role'
    OR auth.uid() = concierge_profile_id
  );

COMMIT;