var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/search/owner-listings/route.js")
R.c("server/chunks/[root-of-the-server]__093dc86b._.js")
R.c("server/chunks/node_modules_b7faa18d._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_0694fa77.js")
R.c("server/chunks/_da86c597._.js")
R.c("server/chunks/node_modules_42103433._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/_next-internal_server_app_api_search_owner-listings_route_actions_44b15095.js")
R.m(27719)
module.exports=R.m(27719).exports
