var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/services/contracts/route.js")
R.c("server/chunks/[root-of-the-server]__6fc8224c._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_b7faa18d._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_da86c597._.js")
R.c("server/chunks/node_modules_42103433._.js")
R.c("server/chunks/_next-internal_server_app_api_services_contracts_route_actions_9a228890.js")
R.m(434777)
module.exports=R.m(434777).exports
