var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/auth/[[...nextauth]]/route.js")
R.c("server/chunks/[root-of-the-server]__b03638bb._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_6a7a9925._.js")
R.c("server/chunks/node_modules_42103433._.js")
R.c("server/chunks/_da86c597._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_next-internal_server_app_api_auth_[[___nextauth]]_route_actions_219b6604.js")
R.m(769027)
module.exports=R.m(769027).exports
