var R=require("../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/provider/interventions/[id]/invoice/route.js")
R.c("server/chunks/[root-of-the-server]__3b304479._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_b7faa18d._.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_da86c597._.js")
R.c("server/chunks/node_modules_42103433._.js")
R.c("server/chunks/ce889_server_app_api_provider_interventions_[id]_invoice_route_actions_10320db8.js")
R.m(257945)
module.exports=R.m(257945).exports
